# Generated by Django 5.1.15 on 2026-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="یادداشت معلم درباره دانش\u200cآموز",
                verbose_name="یادداشت",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="student_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="کد یکتا برای دانش\u200cآموز",
                max_length=20,
                verbose_name="کد دانش\u200cآموزی",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
    ]
