# Generated by Django 5.1.15 on 2026-08-29 05:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0002_classroom_academic_year_classroom_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "student_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="کد دانش\u200cآموزی",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^09\\d{9}$",
                                "شماره موبایل باید با 09 شروع و 11 رقم باشد.",
                            )
                        ],
                        verbose_name="شماره موبایل",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_students",
                        to="classes.classroom",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "دانش\u200cآموز (فهرست کلاس)",
                "verbose_name_plural": "دانش\u200cآموزان (فهرست)",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["classroom", "last_name"],
                        name="students_st_classro_e1fa39_idx",
                    ),
                    models.Index(
                        fields=["student_code"], name="students_st_student_5e7a7e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("student_code__isnull", False),
                            models.Q(("student_code", ""), _negated=True),
                        ),
                        fields=("classroom", "student_code"),
                        name="unique_student_code_per_class",
                    )
                ],
                "unique_together": {("classroom", "student_code")},
            },
        ),
    ]
