# Generated by Django 5.1 on 2026-08-29 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام گروه")),
                (
                    "color",
                    models.CharField(
                        default="#3E9B4F", max_length=7, verbose_name="رنگ"
                    ),
                ),
                (
                    "max_members",
                    models.PositiveIntegerField(default=5, verbose_name="حداکثر اعضا"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="classes.classroom",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="member_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعضا",
                    ),
                ),
            ],
            options={
                "verbose_name": "گروه",
                "verbose_name_plural": "گروه\u200cها",
                "ordering": ["name"],
                "unique_together": {("classroom", "name")},
            },
        ),
    ]
