# Generated by Django 5.1.15 on 2026-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
    ]
