# Generated by Django 5.1 on 2026-08-29 04:33

import apps.classes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام کلاس")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("7", "پایه هفتم"),
                            ("8", "پایه هشتم"),
                            ("9", "پایه نهم"),
                            ("10", "پایه دهم"),
                            ("11", "پایه یازدهم"),
                            ("12", "پایه دوازدهم"),
                            ("other", "سایر"),
                        ],
                        default="10",
                        max_length=10,
                        verbose_name="پایه تحصیلی",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#C22A4E",
                        help_text="HEX color",
                        max_length=7,
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        db_index=True,
                        default=apps.classes.models.generate_invite_code,
                        max_length=6,
                        unique=True,
                        verbose_name="کد دعوت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانش\u200cآموزان",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دبیر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلاس",
                "verbose_name_plural": "کلاس\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invite_code"], name="classes_cla_invite__0cf9bf_idx"
                    ),
                    models.Index(
                        fields=["teacher"], name="classes_cla_teacher_5f9a28_idx"
                    ),
                ],
            },
        ),
    ]
