# Generated by Django 5.1.15 on 2026-08-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="academic_year",
            field=models.CharField(
                blank=True,
                default="1403-1404",
                help_text="مثال: 1403-1404",
                max_length=9,
                verbose_name="سال تحصیلی",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="کلاس فعال/غیرفعال", verbose_name="فعال"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="مثال: ریاضی، علوم",
                max_length=100,
                verbose_name="رشته/درس",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="نام جایگزین - برای سازگاری با مستندات",
                max_length=120,
                verbose_name="عنوان",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(
                help_text="عنوان کلاس", max_length=120, verbose_name="نام کلاس"
            ),
        ),
    ]
