# Generated by Django 5.1 on 2026-08-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان آزمون")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ برگزاری"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=4,
                        verbose_name="نمره کل",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "کوییز"),
                            ("midterm", "میان\u200cترم"),
                            ("final", "پایانی"),
                            ("homework", "تمرین"),
                            ("other", "سایر"),
                        ],
                        default="quiz",
                        max_length=10,
                        verbose_name="نوع آزمون",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classes.classroom",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="lessons.lesson",
                        verbose_name="درس مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "آزمون",
                "verbose_name_plural": "آزمون\u200cها",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن سوال")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=4, verbose_name="بارم"
                    ),
                ),
                (
                    "is_multiple_choice",
                    models.BooleanField(
                        default=False, verbose_name="چهارگزینه\u200cای؟"
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True, verbose_name="گزینه\u200cها (هر خط یک گزینه)"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                        verbose_name="آزمون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوال\u200cها",
            },
        ),
    ]
