# Generated by Django 5.1.15 on 2026-08-29 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
        ("groups", "0002_group_description_group_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_date",
            field=models.DateField(
                blank=True,
                help_text="نام جایگزین برای date",
                null=True,
                verbose_name="تاریخ آزمون",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="groups.group",
                verbose_name="گروه (اختیاری)",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="maximum_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=20,
                max_digits=4,
                null=True,
                verbose_name="حداکثر نمره (مترادف)",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
