# Generated by Django 5.1 on 2026-08-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان درس")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("date", models.DateField(blank=True, null=True, verbose_name="تاریخ")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lessons/",
                        verbose_name="فایل پیوست",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="classes.classroom",
                        verbose_name="کلاس",
                    ),
                ),
            ],
            options={
                "verbose_name": "درس",
                "verbose_name_plural": "درس\u200cها",
                "ordering": ["order", "-date", "-created_at"],
            },
        ),
    ]
