# Generated by Django 5.1.15 on 2026-08-29 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_classroom_academic_year_classroom_is_active_and_more"),
        ("groups", "0002_group_description_group_updated_at_and_more"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="groups.group",
                verbose_name="گروه (اختیاری)",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="homework",
            field=models.TextField(
                blank=True, help_text="تکالیف مربوط به این جلسه", verbose_name="تکالیف"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_date",
            field=models.DateField(
                blank=True,
                help_text="نام جایگزین برای date - سازگار با مستندات",
                null=True,
                verbose_name="تاریخ درس",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ جلسه"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["classroom", "group"], name="lessons_les_classro_a14eff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["date"], name="lessons_les_date_63f5f0_idx"),
        ),
    ]
