# Generated by Django 5.1 on 2026-08-29 04:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="نمره",
                    ),
                ),
                (
                    "comment",
                    models.CharField(blank=True, max_length=200, verbose_name="توضیح"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="exams.exam",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمره",
                "verbose_name_plural": "نمرات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["exam", "student"],
                        name="scores_scor_exam_id_a7530b_idx",
                    )
                ],
                "unique_together": {("exam", "student")},
            },
        ),
    ]
