# Generated by Django 5.1.15 on 2026-08-29 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_exam_exam_date_exam_group_exam_maximum_score_and_more"),
        ("scores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت"),
        ),
        migrations.AddField(
            model_name="score",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="نمره (مترادف)",
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)), name="score_value_gte_0"
            ),
        ),
    ]
